apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rolloutapp
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rolloutapp
  template:
    metadata:
      labels:
        app: rolloutapp
    spec:
      containers:
      - image: salesdemocf/express-microservice:e3bbca2
        name: rolloutapp
        ports:
        - containerPort: 3000
  minReadySeconds: 30
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {}
